// <auto-generated />
namespace BlueWind.Crawler.Manga.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ChangeThumbnailFormat : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChangeThumbnailFormat));
        
        string IMigrationMetadata.Id
        {
            get { return "201404080225155_ChangeThumbnailFormat"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
